name: Benchmark Comparison

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  id-token: write

jobs:
  runner-start:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::800406105498:role/RafaelGSS-nodejs-bench-operations
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Runner
        uses: nodesource/aws-eco-runner@v1.0.0-beta.3
        with:
          instances_id: '["i-065f0f848eb1615ae"]'
          action: 'start'
          aws_default_region: 'us-west-2'

  benchmark:
    name: Run Benchmark Comparisons
    runs-on: self-hosted
    continue-on-error: true

    strategy:
      matrix:
        node-version: [20, 22, 24]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install --dev
      
      - name: Run basic comparison
        run: node --allow-natives-syntax examples/benchmark-comparison/comparison.js
